language: go

go:
  - "1.10.x"

before_install:
  - go get github.com/mitchellh/gox

install: true

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...
  - go test -v -race ./...
  - gox -os="linux darwin windows" -arch="amd64" -output="sampletee.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose .

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Mu1if8V5Myqiz0/jiQAiZGE/7ygix9MNbDGFWAZzQtrVklF+SFsRctaV8Jj6UmRVw4i0FGvR9ePAly/oWh914fzKh7rra85JAzbPZ+asPEHBP7dlBsBE29pIyOufvNWnX8WmKGyTVdVgAvAFdmTGnaxq28OZ+YfJFThqqO/uuucnSkD4KviJhxs1ZSH/IH1kEw1LhYkO9v8rTXr8ogq0Ed8AfziNAOnXw2d09/ZkAoVW1ys7OnCF1WEbqXZUKxkdW+NuKJSz2O/ET4ztWJuWGugAWsL8Lv8hGFCIuxWExdkZODheEJZsERaFigvycbStOJWLanLXmvcYuP6LPH6/uMSnsg7sEsEkNPi41kkAo1QVm57VeBSLtBj4pTU5z99BZj38d+UMHlA+Dpbsv4p2Sv5Qlut7o2Ie7G6XHHz4CN294PWpIVYEofS0QGC69zWGx2dGZOCZmgk2CuLXFpvcUGYrzG1NmAW1UJI5Ci3Nl5+wF75uE1t7iHIbBiMKzGhqB0i8514jnum0TXQ7T20SSJ4hP2l/3R0p44fUQQjIt1QAbDiA/Z5AkA7axJCNsfk2cuq56GA8vK1aOWYC7IgzVTUM+Ua/e/+JHZ/ska9MYuCHWhRUESl9I90yOWfltY4PtSyf9SAEjJcxCWC7ZLNeCIYCQwkf8LGYlzV7+l2j6Zs=
  file:
    - sampletee.linux.amd64
    - sampletee.darwin.amd64
    - sampletee.windows.amd64
  on:
    repo: adamwg/sampletee
    branch: master
    tags: true
