language: go

go:
  - "1.10.x"

before_install:
  - go get github.com/mitchellh/gox

install: true

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet ./...
  - go test -v -race ./...
  - gox -os="linux darwin windows" -arch="amd64" -output="sampletee.." -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose .

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "Fbm1EMzDTOTznkXdlof6g6V3TYkdMt+GshUTr6aM08KRdCehYmN+ONdA8jvcc/9XaaoYEIwG3m/g0pO/Q+XRHxZNQZwW4CbQ5nRyoCiuIVlC0RIg7pefc6GkIrSyJ4nlZKmdz2Ba89u4gbQVmPnKiUFzoXJRR9ktU1nNM2FzZgs/LrUb9PmOW9uBGYVhesrW2jvd2VHccl1QfdAPJ6M80LiplHpPayCosfKz3fEKq9FWQ/Fx6akZVDaHX8GOgXeSfK1ZQ/kfO0OEJk/AzWoaHjqxqywbmmZWwhuzNsFQvvzyW0w1mo2DJBtaVcE/jBFlQoqWAB1VMxHyc5idh8MDm7vWzbIkAl/bBIQXfrou6kTzMrcZK0VR6KV9AGqJe767zdHtXCDNanozw9akjKKHisPelQwnCFs5eRMjLsADfqjDLdACuydvxvhQPZJucXJFNeift8Mhc6znmSjQiByRNdJb0Lft6usyckcBbnYE2cs4W1ccdnA5JGz9mx+IQ3Jyi83ZZgCbxQ5YVZXctSWSeD0Z/wsVxkCoZ6MRMB0xs8xQSjSM1D1U1iAaEBFvL94EfnVo0AF1FPwoLZGhZ+xENJBeUq7eyEnTgJQQoM5vtO/v54WLUHpRGpiml26cQT1jyvsjKsCxnZYB+FPplTtv978dpuR7ZorcYLXAcgfHPlY="
  file:
    - sampletee.linux.amd64
    - sampletee.darwin.amd64
    - sampletee.windows.amd64
  on:
    repo: adamwg/sampletee
    branch: master
    tags: true
